name: Java CD with Maven

on:
  push:
    branches: [ main ]  # Jalankan saat push ke branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy (simulasi copy file)
      run: |
        echo "Simulasi deploy: Copy file ke folder output"
        mkdir -p deployment
        cp target/*.jar deployment/
