name: Java Maven CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven (di subfolder)
      run: |
        cd Basic-Java-Maven-main-SCD
        mvn clean install

    - name: Simulasi Deploy
      run: |
        cd Basic-Java-Maven-main-SCD
        mkdir -p simulasi-deploy
        cp target/*.jar simulasi-deploy/
